### ISSUE TITLE
Message Request Builder doesn't return all messages

### ISSUE THREAD

**Issue by shiroganee** [cometchat-pro/react-native-chat-sdk#18]
### Describe the problem

I've according to docs following function
> CometChat.MessagesRequestBuilder().setLimit(50).setUID(receiverId).build()
when doing fetchPreviously(), I'm not getting a message that I created between my user and that with receiverId. Odd thing, is that sometimes for other profiles - it is reported

### What was the expected behavior?

Return all messages up to limit for specific ReceiverId

### Reproduction

Create message between user X and Y from API, later on fetch all messages between them from one of profiles, at some times the message is not available for some users

### Environment

> Please provide the following:

Version: 2.0.13-beta1

**Comment by mayur-bhandari** [comment]
Hello @shiroganee ,

We did follow the steps you have mentioned above to reproduce the issue. But everything seems to be working fine on our end.  Can you please share the API endpoint you are using to send message. Also, it would be really helpful if you could share appId and region and uids (uid of sender and receiver of the message) with us so that we can get this checked on our end.

Also, I would advice you to update to the latest SDK v2.1.0. Starting v2.1.0, you need to follow the setup docs to ensure that the SDK works seamlessly. Please follow the documentation [here](https://prodocs.cometchat.com/docs/react-native-setup).

**Comment by shiroganee** [comment]
I cleared all users, all messages and registered all users anew and it seems to be alright now so I cannot reproduce it locally. If I will encounter it again then I will reopen an issue. Thanks for quick answer

**Comment by shiroganee** [comment]
Okey it happened again sadly @mayur-bhandari 
I'm using

`
const textMessage = new CometChat.TextMessage(receiverId, message, CometChat.RECEIVER_TYPE.USER);
  return CometChat.sendMessage(textMessage);
`

AppId: 20675057cf11ef8
region: US
user ids: mab9nrou7y with crgllzshdu and cvqcwlam3a with crgllzshdu

**Comment by shiroganee** [comment]
@mayur-bhandari
